In [16]:
with open('./dataset/input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# print(text)

In [17]:
# next we need to create a tokenizer
# the tokenizer will create a vocabulary for the input data
# we will be using the tiktoken tokenizer, which is a byte pair encoding (BPE) tokenizer
import tiktoken
# here we are using a pre-trained tokenizer that is compatible with the GPT-2 model
# benefit of using a pre-trained tokenizer is that it will have a larger vocabulary and will be able to encode more words
# we can also train our own tokenizer, as that better suits our specific dataset
# a bpe tokenizer will break down words into subwords, which allows it to handle out-of-vocabulary words better
# the way a bpe 
# how is a simple tokenizer trained?
# the most simple form of tokenizer is a character-level tokenizer, which simply splits the text into individual characters
# the then trained tokenizer can then be used to encode the text into a sequence of integers, which can then be fed into the model
# so when we use a pre-trained tokenizer, we are using a tokenizer that has already been trained on a large corpus of text, and has a fixed vocabulary
# the tiktoken library provides a simple interface for encoding and decoding text using the pre-trained tokenizer
tokenizer = tiktoken.get_encoding('gpt2')
# we can then use the tokenizer to encode the text into a sequence of integers
encoded_text = tokenizer.encode(text)
print(encoded_text[:100])  # print the first 100 tokens

[5962, 22307, 25, 198, 8421, 356, 5120, 597, 2252, 11, 3285, 502, 2740, 13, 198, 198, 3237, 25, 198, 5248, 461, 11, 2740, 13, 198, 198, 5962, 22307, 25, 198, 1639, 389, 477, 12939, 2138, 284, 4656, 621, 284, 1145, 680, 30, 198, 198, 3237, 25, 198, 4965, 5634, 13, 12939, 13, 198, 198, 5962, 22307, 25, 198, 5962, 11, 345, 760, 327, 1872, 385, 1526, 28599, 318, 4039, 4472, 284, 262, 661, 13, 198, 198, 3237, 25, 198, 1135, 760, 470, 11, 356, 760, 470, 13, 198, 198, 5962, 22307, 25, 198, 5756, 514, 1494, 683, 11, 290, 356]


In [ ]:
# so now we have the classic question of tensors:
# the data, should be living as on a tensor on GPU
# we can use the PyTorch library to create a tensor from the encoded text
import torch
# we can create a tensor from the encoded text
# we need to specify the data type of the tensor, which is usually torch.long for integer
encoded_text_tensor = torch.tensor(encoded_text, dtype=torch.long)
print(encoded_text_tensor[:100])  # print the first 100 tokens as a tensor
# but we also need to move the tensor to the GPU, so that it can be used for training the model
# but initially let's keep the data on the CPU, and we can move it to the GPU later when we are ready to train the model
# what benefit does tensor provide over a simple list of integers?
# tensors are optimized for performance and can be easily moved to the GPU for faster computation, lists of integers are not optimized for performance and cannot be easily moved to the GPU
   

tensor([ 5962, 22307,    25,   198,  8421,   356,  5120,   597,  2252,    11,
         3285,   502,  2740,    13,   198,   198,  3237,    25,   198,  5248,
          461,    11,  2740,    13,   198,   198,  5962, 22307,    25,   198,
         1639,   389,   477, 12939,  2138,   284,  4656,   621,   284,  1145,
          680,    30,   198,   198,  3237,    25,   198,  4965,  5634,    13,
        12939,    13,   198,   198,  5962, 22307,    25,   198,  5962,    11,
          345,   760,   327,  1872,   385,  1526, 28599,   318,  4039,  4472,
          284,   262,   661,    13,   198,   198,  3237,    25,   198,  1135,
          760,   470,    11,   356,   760,   470,    13,   198,   198,  5962,
        22307,    25,   198,  5756,   514,  1494,   683,    11,   290,   356])
tensor([ 5962, 22307,    25,   198,  8421,   356,  5120,   597,  2252,    11,
         3285,   502,  2740,    13,   198,   198,  3237,    25,   198,  5248,
          461,    11,  2740,    13,   198,   198,  5962, 22307,

In [23]:
import tiktoken
import torch
tokenizer = tiktoken.get_encoding('gpt2')
data = torch.tensor(tokenizer.encode(text), dtype=torch.long)
data[:1000]

tensor([ 5962, 22307,    25,   198,  8421,   356,  5120,   597,  2252,    11,
         3285,   502,  2740,    13,   198,   198,  3237,    25,   198,  5248,
          461,    11,  2740,    13,   198,   198,  5962, 22307,    25,   198,
         1639,   389,   477, 12939,  2138,   284,  4656,   621,   284,  1145,
          680,    30,   198,   198,  3237,    25,   198,  4965,  5634,    13,
        12939,    13,   198,   198,  5962, 22307,    25,   198,  5962,    11,
          345,   760,   327,  1872,   385,  1526, 28599,   318,  4039,  4472,
          284,   262,   661,    13,   198,   198,  3237,    25,   198,  1135,
          760,   470,    11,   356,   760,   470,    13,   198,   198,  5962,
        22307,    25,   198,  5756,   514,  1494,   683,    11,   290,   356,
         1183,   423, 11676,   379,   674,   898,  2756,    13,   198,  3792,
          470,   257, 15593,    30,   198,   198,  3237,    25,   198,  2949,
          517,  3375,   319,   470,    26,  1309,   340,   307, 

In [27]:
xt = data[:32]
xt = xt.reshape(4,8)
print(xt)
# what will yt be?
# yt becomes everything from data[1:33]
yt = data[1:33]
print(yt)

tensor([[ 5962, 22307,    25,   198,  8421,   356,  5120,   597],
        [ 2252,    11,  3285,   502,  2740,    13,   198,   198],
        [ 3237,    25,   198,  5248,   461,    11,  2740,    13],
        [  198,   198,  5962, 22307,    25,   198,  1639,   389]])
tensor([22307,    25,   198,  8421,   356,  5120,   597,  2252,    11,  3285,
          502,  2740,    13,   198,   198,  3237,    25,   198,  5248,   461,
           11,  2740,    13,   198,   198,  5962, 22307,    25,   198,  1639,
          389,   477])


In [43]:
block_size = 8
batch_size = 4
def get_batch(split=None):
    # lets first build the most simple one:
    # here we get only a single xb, and yb set
    # we first need to know the length of our context: block_size # defined as 8
    # we need a starting index 
        # conditions for starting index: random
        # sample space: 
        # n is data length, say we n = 100
        # start idx, can be 0 ... 100-block_size-1, -1 is because xy, is idx+1
    # why do we need a split?
    # split so that we take data based on training data or validation data

    start_idx = torch.randint(len(data)-block_size-1, (batch_size,))
    print(start_idx)
    x = torch.stack([data[idx:idx+block_size] for idx in start_idx])
    y = torch.stack([data[idx+1:idx+1+block_size] for idx in start_idx])
    return x,y

get_batch()

tensor([ 40173,  52554, 247766, 306631])


(tensor([[49275,  1677,    40,  2937,    25,   198, 19242,   339],
         [  198,    38,  3525,  2538, 49275,    25,   198,    51],
         [11240,   198, 17584,  3447,  1626,   502,    11,   290],
         [  507,  6478,  1549,   351, 43836,    11,   198,  7762]]),
 tensor([[ 1677,    40,  2937,    25,   198, 19242,   339,   288],
         [   38,  3525,  2538, 49275,    25,   198,    51,   322],
         [  198, 17584,  3447,  1626,   502,    11,   290,   777],
         [ 6478,  1549,   351, 43836,    11,   198,  7762,   590]]))

In [44]:
import torch
import torch.nn as nn
from torch.nn import functional as F


In [48]:
x = torch.tensor([[1.,2.],[1.,2.]])
y = torch.tensor([1.,2.])
print(x.shape, y.shape)


torch.Size([2, 2]) torch.Size([2])


In [49]:
F.cross_entropy(x,y)

RuntimeError: expected scalar type Long but found Float

In [ ]:
input = torch.randn(2, 2)
target = torch.randint(2, (2,))
loss = F.cross_entropy(input, target)

torch.Size([2, 2]) torch.Size([2])


In [53]:
loss

tensor(2.3973)

In [57]:
xb_gen = torch.tensor([[0]])
xb_gen.shape

torch.Size([1, 1])

In [58]:
tokenizer.decode([    0, 31323, 33718, 28810,  2838, 30392])

'! grips tornado discreteuary Lak'

In [64]:
gen = torch.randn((1,11))
gen[0]

tensor([ 1.3896, -2.3719,  0.8496,  0.6860,  0.5306, -0.2390, -0.4570, -0.8141,
        -0.1233,  1.0522, -0.5896])

In [ ]:
print(50%2)

0


In [54]:
import torch
q = torch.randn((8,32))
k = torch.randn((8,32))
wei = q@k.transpose(-2,-1)

In [55]:
wei.shape

torch.Size([8, 8])

In [56]:
print(wei)

tensor([[-12.3396,  -1.8697,  -6.6075,  -9.5193,   4.5048,  -6.8611,  -4.0603,
          -8.0448],
        [ -9.3739,  -3.3798,  -1.2555,  -2.7470,   0.9154,  -5.0574,   1.7313,
          -0.9399],
        [ -3.9810,  -0.8676,  -2.9985,   3.5672, -11.9233,  -5.2274,   3.5128,
           1.8442],
        [ 11.8154,   2.6259,   5.5534,   3.6237,   2.9752,  11.5664,  -4.5203,
           3.8890],
        [ -2.6912,  -2.0927,   1.6342,   0.3273,  -1.5107,  -0.8863,   7.8019,
           7.8119],
        [  5.0138,   6.4403,  -5.8503,   0.3843,   2.0435,   1.6804,  -2.3955,
          -6.4705],
        [  2.6709,  -1.6304,   2.8961,   3.5227,   5.0572,   0.7004,  -6.9614,
          -3.2831],
        [  5.3695,   3.0049,   0.4189,   2.8626,   9.4264,   0.9601,   1.8548,
           8.9606]])


In [57]:
tril = torch.tril(torch.ones(8,8))
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
wei = wei.masked_fill(tril==0, float('-inf'))
wei

tensor([[-12.3396,     -inf,     -inf,     -inf,     -inf,     -inf,     -inf,
             -inf],
        [ -9.3739,  -3.3798,     -inf,     -inf,     -inf,     -inf,     -inf,
             -inf],
        [ -3.9810,  -0.8676,  -2.9985,     -inf,     -inf,     -inf,     -inf,
             -inf],
        [ 11.8154,   2.6259,   5.5534,   3.6237,     -inf,     -inf,     -inf,
             -inf],
        [ -2.6912,  -2.0927,   1.6342,   0.3273,  -1.5107,     -inf,     -inf,
             -inf],
        [  5.0138,   6.4403,  -5.8503,   0.3843,   2.0435,   1.6804,     -inf,
             -inf],
        [  2.6709,  -1.6304,   2.8961,   3.5227,   5.0572,   0.7004,  -6.9614,
             -inf],
        [  5.3695,   3.0049,   0.4189,   2.8626,   9.4264,   0.9601,   1.8548,
           8.9606]])

In [ ]:
from torch.nn import functional as F
wei= wei.softmax(dim=-1)
wei.shape

torch.Size([8, 8])

In [62]:
v = torch.randn((8,6))

In [63]:
out = wei@v

In [64]:
out.shape

torch.Size([8, 6])

In [ ]:

y = torch.ones(8,8))
y

SyntaxError: unmatched ')' (231900935.py, line 2)

In [93]:
import torch.nn as nn
emb = nn.Embedding(8,8)

In [97]:
x = torch.arange(8)

emb(x)

tensor([[ 0.7230, -0.3897,  0.8222, -0.7296, -1.4103,  2.6003,  1.6355,  0.6457],
        [ 0.7027, -0.7290, -0.7825,  1.0254, -0.6997, -0.2206,  0.5723, -0.5669],
        [ 0.1758,  0.3886, -0.1505,  0.0661,  1.6394,  0.0651, -0.8488,  0.4923],
        [ 1.9166, -0.1801, -0.3310,  1.4887,  1.0874,  0.5270, -0.2931, -0.0756],
        [-2.3356,  0.2261,  0.3562, -0.1693,  0.2833,  0.2317,  1.8672, -0.2479],
        [-0.0871, -1.8828, -0.6361,  1.6267,  1.3452,  0.2921, -0.2148,  0.6825],
        [-0.0372,  2.0466,  0.1868, -0.1808, -0.4078,  1.7852,  1.0629, -0.0117],
        [-0.4470, -0.5739, -0.4598, -1.2910, -1.1987, -0.6187,  0.9039,  0.9083]],
       grad_fn=<EmbeddingBackward0>)